version: '3'

tasks:
  switch:darwin:
    cmds:
      - home-manager switch --flake .#taiseiue@darwin
  switch:linux:
    cmds:
      - home-manager switch --flake .#taiseiue@linux
  update:
    cmds:
      - nix flake update --flake ./ && git commit -am "Update flake lock" && git push
