version: '3'

tasks:
  update:
    cmds:
      - nix flake update --flake ./ && git commit -am "Update flake lock" && git push
    clean:
      cmds:
        - nix-collect-garbage --delete-older-than 7d && nix-store --gc
  switch:lily:
    cmds:
      - home-manager switch --flake .#taiseiue@lily
  switch:leica:
    cmds:
      - home-manager switch --flake .#taiseiue@leica
  switch:linux:
    cmds:
      - home-manager switch --flake .#taiseiue@linux
  switch:mac:
    cmds:
      - task: switch:darwin
